export const UPDATE_STUDENT_DATE ='UPDATE_STUDENT_DATE';
export const DELETE_STUDENT_DATE ='DELETE_STUDENT_DATE';
export const ADD_STUDENT_DATE ='ADD_STUDENT_DATE';
export const GET_STUDENT_DATE ='GET_STUDENT_DATE';
